__author__ = "Guilherme Castelao"
__email__ = "guilherme@castelao.net"

from .cnv import CNV, fCNV
from .exceptions import CNVError

# __all__ = ['CNV', 'fCNV']

from importlib import metadata, resources

try:
    from importlib.metadata import version, PackageNotFoundError
except ImportError:  # Python < 3.8
    from importlib_metadata import version, PackageNotFoundError  # type: ignore

try:
    __version__ = version(__name__)
except PackageNotFoundError:
    try:
        from .version import version as __version__
    except ImportError as exc:
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs; "
            "use the PyPI distributions instead."
        ) from exc
